### ISSUE TITLE
Build Failed

### ISSUE THREAD

**Issue by marclundgren** [jsdf/ReactNativeHackerNews#1]
Cool repo! I'd like to view the demo, but I'm having a hard time building in xcode. Below is the error I noticed after `npm install`...

![screen shot 2015-04-18 at 3 03 14 pm](https://cloud.githubusercontent.com/assets/1154834/7217264/1dd1bfee-e5dc-11e4-9651-4e19a2b0a207.png)

**Comment by jsdf** [comment]
I've pushed a version which should 'just work', but read this page on the React Native docs for more info: http://facebook.github.io/react-native/docs/runningondevice.html#content

**Comment by marclundgren** [comment]
I'm still seeing this error. Also, I'm using the xcode simulator, not my device.

**Comment by jsdf** [comment]
Oh, right, I forgot to remove the reference to main.jsbundle from the XCode project's files list. I've pushed a new commit which removes it, or you can just remove it from the XCode project yourself, or touch the file so it exists.

**Comment by marclundgren** [comment]
@jsdf, thanks! The build succeeds now
